config/routes.rb
Rails.application.routes.draw do
  get 'bme280/:id' => 'bme280#show_graph', as: :bme280
  get 'bme280/data/:id' => 'bme280#show_graph_data', as: :bme280_data
  get 'bme280/raw/:id' => 'bme280#show_raw', as: :bme280_raw

  get 'webcam/:id' => 'webcam#show_images', as: :webcam
  get 'webcam/:id/:date' => 'webcam#show_images_day', as: :webcam_day

  get 'pages/root'
  root 'pages#root'

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bme280_controller.rb
class Bme280Controller < ApplicationController
  def index
    # TODO: list all raspi_id on logs table.
  end

  def show_graph
    id = params[:id]
    db = connect_bme280
    st = (DateTime.now - 1.days).strftime("%F %T")
    en = DateTime.now.strftime("%F %T")
    # Get stat.
    sql = "SELECT count(1) AS c,min(ts) AS mi,max(ts) AS ma FROM bme280_logs WHERE raspi_id = #{id}"
    results = db.query(sql)
    row = results.first
    @count = row["c"]
    raise "No record found for raspi_id=#{id}" if @count == 0
    @min = row["mi"].strftime("%F")
    @max = row["ma"].strftime("%F %T")
    @days = ((row["ma"] -  row["mi"]) / 64800).floor
    st,en = get_span
    @span = "from "+st+" to "+en
    @id = id

    # Taking over parameter to show_graph_data action.
    @p = {id: params[:id], day_offset: params[:day_offset]}
    @p = @p.to_json.html_safe
  end

  def show_graph_data
    id = params[:id]
    src = params[:src] || "temperature"
    unit = params[:unit] || "10min"
    db = connect_bme280
    if unit == "day" # 1day
      @data = {avg: [], max: [], min: [], diff: []}
      sql = "SELECT ts,#{src}_avg,#{src}_max,#{src}_min FROM bme280_logs_dailies WHERE raspi_id = #{id} ORDER BY ts"
      results = db.query(sql)
      results.each do |row|
        ts = (row["ts"].to_time.to_i + 9 * 60 * 60) * 1000
        @data[:avg] += [[ts,row[src+"_avg"]]]
        @data[:max] += [[ts,row[src+"_max"]]]
        @data[:min] += [[ts,row[src+"_min"]]]
        @data[:diff] += [[ts,row[src+"_max"] - row[src+"_min"]]]
      end
    else # 10min
      @data = []
      st,en = get_span
      sql = "SELECT ts,#{src} FROM bme280_logs WHERE raspi_id = #{id} AND ts BETWEEN '#{st}' AND '#{en}' ORDER BY ts"
      db = connect_bme280
      results = db.query(sql)
      results.each do |row|
        # @data += [["Date.parse('"+row["ts"].to_s+"')",row[src]]]
        @data += [[(row["ts"].to_i + 9 * 60 * 60) * 1000,row[src]]]
      end
    end
    respond_to do |format|
      format.json { render json: @data }
    end
  end

  def show_raw
    id = params[:id]
    db = connect_bme280
    st = (DateTime.now - 30.days).strftime("%F %T")
    en = DateTime.now.strftime("%F %T")
    sql = "SELECT * FROM bme280_logs WHERE raspi_id = #{id} AND ts BETWEEN '#{st}' AND '#{en}' ORDER BY ts"
    @results = db.query(sql)
    respond_to do |format|
      format.html
      format.csv do
        filename = "bme280_#{id}.csv"
        headers["Content-Type"] ||= 'text/csv'
        headers["Content-Disposition"] = "attachment; filename=\"#{filename}\""
        render layout: false
      end
    end
  end

  private
    def connect_bme280
      client = Mysql2::Client.new(host:"localhost",username:"root",database:"sandbox-rails_"+Rails.env)
    end

    def get_span
      day_offset = (params[:day_offset] || "0").to_i
      st = (DateTime.now - (day_offset + 1).days).strftime("%F %T")
      en = (DateTime.now - day_offset.days).strftime("%F %T")
      return [st, en]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def root
  end
end

app/controllers/webcam_controller.rb
class WebcamController < ApplicationController
  DIR = "/opt/webcamlogs"

  def show_images
    id = params[:id]
    db = ActiveRecord::Base.connection
    st = (DateTime.now - 1.days).strftime("%F %T")
    en = DateTime.now.strftime("%F %T")
    # Get stat.
    sql = "SELECT ts,n,(SELECT ts FROM webcam_logs WHERE id = max_marks_id) AS mts FROM webcam_logs_dailies WHERE webcam_id = '#{id}' ORDER BY ts DESC"
    @data = []
    results = db.execute(sql)
    results.each do |row|
      @data += [{ts: row[0], n: row[1], path: to_path(id,row[2])}]
    end
    @id = id
  end

  def show_images_day
    id = params[:id]
    date = params[:date]
    db = ActiveRecord::Base.connection
    sql = "SELECT ts,marks,memo FROM webcam_logs WHERE webcam_id = '#{id}' AND date(ts) = '#{date}' ORDER BY ts DESC"
    @data = []
    results = db.execute(sql)
    results.each do |row|
      @data += [{ts: row[0], marks: row[1], path: to_path(id,row[0]),memo: row[2]}]
    end
    @id = id
  end

  private
    def to_path(id,ts)
      "/webcamlogs/#{id}/"+ts.strftime("%y%m%d_%H%M%S")+".jpg"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def list_group_item(head,body,path)
    text = '<p class="list-group-item-heading">'+head+'</p>'
    text += '<p class="list-group-item-text text-muted">'+body+'</p>'
    link_to text.html_safe, path, class: "list-group-item"
  end
end

app/views/bme280/index.csv.erb
UID,RASPI_ID,TIMESTAMP,TEMPERATURE,PRESSURE,HUMIDITY,MODIFIED_AT
<% @results.each(as: :array) do |row| %>
<%= row.join(",") %>
<% end %>

app/views/bme280/show_graph.html.erb
<% content_for :title do %>BME280<% end %>
<table class="table">
  <tr>
    <th>RaspberryPi ID</th>
    <td><%= @id %></td>
    <th>件数</th>
    <td><%= @count %></td>
    <th>保存期間</th>
    <td><%= @min %> to <%= @max %> (<%= @days %> days)</td>
  </tr>
</table>
<p><%= link_to 'Download CSV', bme280_raw_path(@id,format: :csv), class: "btn btn-default" %></p>
<div class="row">
<div id="chart_t" class="col-md-4"></div>
<div id="chart_h" class="col-md-4"></div>
<div id="chart_p" class="col-md-4"></div>
<small><%= @span %></small>
<div>
<div class="row">
  <div id="chart_dt" class="col-md-12"></div>
<div>
<script>
  $.getJSON('data/<%= @id %>.json?src=temperature', <%= @p %> ,function (data) {
    $('#chart_t').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: '気温 (°C)',
        },
        xAxis: {
            type: 'datetime'
        },
        yAxis: {
            title: {
                text: ''
            }
        },
        series: [{
            name: "気温",
            color: Highcharts.getOptions().colors[3],
            showInLegend: false,
            data: data
        }]
    });
  });
  $.getJSON('data/<%= @id %>.json?src=humidity', <%= @p %> , function (data) {
    $('#chart_h').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: '湿度 (%)',
        },
        xAxis: {
            type: 'datetime'
        },
        yAxis: {
            title: {
                text: ''
            }
        },
        series: [{
            name: '湿度',
            color: Highcharts.getOptions().colors[0],
            showInLegend: false,
            data: data
        }]
    });
  });
  $.getJSON('data/<%= @id %>.json?src=pressure', <%= @p %> , function (data) {
    $('#chart_p').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: '気圧 (hPa)',
        },
        xAxis: {
            type: 'datetime'
        },
        yAxis: {
            title: {
                text: ''
            }
        },
        series: [{
            name: '気圧',
            color: Highcharts.getOptions().colors[2],
            showInLegend: false,
            data: data
        }]
    });
  });
  $.getJSON('data/<%= @id %>.json?unit=day', <%= @p %> , function (data) {
    $('#chart_dt').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: '気温 (°C)',
        },
        xAxis: {
            type: 'datetime'
        },
        yAxis: [{
          title: {
            text: ''
          }
        },{
          title: {
            text: ''
          },
          opposite: true
        }],
        series: [{
            name: "気温差",
            color: Highcharts.getOptions().colors[6],
            showInLegend: true,
            data: data.diff,

            type: 'area',
            yAxis: 1
        },{
            name: "最高気温",
            color: Highcharts.getOptions().colors[3],
            showInLegend: true,
            data: data.max
        },{
            name: "最低気温",
            color: Highcharts.getOptions().colors[4],
            showInLegend: true,
            data: data.min
        }]
    });
  });
</script>

app/views/bme280/show_raw.csv.erb
UID,RASPI_ID,TIMESTAMP,TEMPERATURE,PRESSURE,HUMIDITY,MODIFIED_AT
<% @results.each(as: :array) do |row| %>
<%= row.join(",") %>
<% end %>

app/views/bme280/show_raw.html.erb
<table>
  <tr>
    <th>UID,RASPI_ID,TIMESTAMP,TEMPERATURE,PRESSURE,HUMIDITY,MODIFIED_AT</th>
  </tr>
<% @results.each(as: :array) do |row| %>
<tr>
  <td>
<%= row.join(",") %></td>
</tr>
<% end %>
</table>

app/views/layouts/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "<span class='glyphicon glyphicon-grain'></span> LM Rails".html_safe, root_path, class: "navbar-brand" %>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
			</ul>
		</div><!--/.nav-collapse -->
	</div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LM Rails - <%= content_for(:title) || "No title" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="https://code.highcharts.com/4.1.8/highcharts.js"></script>
</head>
<body>
  <div class="container">
    <%= render 'layouts/navbar' %>
    <% if notice %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-warning"><%= alert %></p>
    <% end %>

    <%= yield %>

    <footer class="footer">
      <a href="http://www.lumber-mill.co.jp/notes/">LumberMill, Inc.</a>
    </footer>
  </div>
</body>
</html>

app/views/pages/root.html.erb
<% content_for :title do %>Main menu<% end %>
<div class="row">
  <div class="col-md-4">
    <div class="list-group">
      <%= list_group_item "BME280 at 452","since 2015.09<br/>ラズベリーパイで収集した気温・湿度・気圧の記録",bme280_path(0) %>
      <%= list_group_item "BME280 at greenhouse","since 2016.01<br/>ラズベリーパイで収集した気温・湿度・気圧の記録",bme280_path(1) %>
      <%= list_group_item "Webcam at 国見ヶ丘","since 2015.09",webcam_path("kunimi") %>
      <%= list_group_item "Webcam at 高千穂峡","since 2015.09",webcam_path("gorge") %>
    </div>
  </div>
  <div class="col-md-8">
    <h3>ここは何?</h3>
    <p>BME280はRaspberry Piに接続して気温・湿度・気圧を測定できるセンサです。
    これを使って定点観測をしたデータをグラフ化しています。CSVでデータを一括ダウンロードすることも可能です。
    「Webcam at..」のページでは、高千穂町に設置・公開されているウェブカムのスナップショットを定期的に
  　　収集したデータを表示しています。毎日AM5:00から7:45まで、15分おきに記録しています。</p>
    <p><a href="http://lmlab.net">http://lmlab.net</a></p>
  </div>
</div>

<p></p>

app/views/webcam/show_images.html.erb
<% content_for :title do %>Kunimigaoka<% end %>
<p><%= @files.count %> files.</p>
<div class="row">
<% @files.reverse.each do |f| %>
  <div class="col-md-4">
  <%= image_tag "/webcamlogs/"+f,class: "img-responsive img-rounded" %>
  <small><%= f %></small>
  </div>
<% end %>
</div>

app/views/webcam/show_images_day.html.erb
<% content_for :title do %><%= @id %><% end %>
<h1><%= @id %></h1>
<div class="row">
  <% @data.each do |row| %>
  <div class="col-md-4">
  <%= image_tag(row[:path],class: "img-responsive img-rounded")  %>
  <small><%= row[:ts] %>, <%= row[:marks] %> <%= row[:memo] %></small>
  </div>
  <% end %>
</div>